### ISSUE TITLE
Import Cyphal/CAN from older UAVCAN filter

### ISSUE THREAD

**Issue by emrainey** [OpenCyphal-Garage/wireshark_plugins#2]
The older filter was written in C so a new filter will have to be rewritten from scratch in Lua if we want that. UDP was very easy in Lua so a working CAN version can't be too hard.

**Comment by pavel-kirienko** [comment]
Why would we want to rewrite a working dissector in another language though? I think its only problem right now is that it is named improperly (UAVCAN/CAN instead of Cyphal/CAN).

**Comment by emrainey** [comment]
Keeping them together reduces the support burden for updating the specification. Currently that dissector is in Peter's github and is thousands of commits older than the most up to date wireshark (which has a copy of uavcan-can too). 

Learning Lua last night was fairly simple. It's not a complex language, but it is a bit hard to debug inside Wireshark.

**Comment by pavel-kirienko** [comment]
I see your point but note that Peter's dissector has already been accepted upstream so the fact that his fork is falling behind is not relevant.
